apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-app
  template:
    metadata:
      labels:
        app: eks-app
    spec:
      containers:
      - name: eks-app
        image: 339772065903.dkr.ecr.ap-south-1.amazonaws.com/eks-devops-app
        ports:
        - containerPort: 3000
